import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const revalidateCoins = async () => {
  const res = await fetch("/api/revalidation?secret=mytoken");
  console.log("res: ", res);
  return res;
};

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Link href="/coins">Coins List</Link>
          <button onClick={() => revalidateCoins()}>
            {"revalidate '/coins'"}
          </button>
        </div>
      </main>
    </>
  );
};

export default HomePage;
